apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway.yaml
  - route.yaml

images:
  - name: ghcr.io/example/hello-enterprise
    newName: ghcr.io/mdkatz97/hello-enterprise
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
